### ISSUE TITLE
Update plot when some settings are updated. Plot spectrum button not working.

### ISSUE THREAD

**Issue by Harrinive** [scqubits/qfit#11]
For example, pre-fit settings (init state, transition, etc). 
Plot spectrum button is not working as well. There is possibly a bug.

**Comment by ZhaoTianPu** [comment]
Traced the issue and suspect that the culprit is at `onPrefitPlotClicked `, line 1084 of the mainwindow.py, with exception:
TypeError: QuantumModel.sweep2SpecNMSE() missing 2 required positional arguments: 'slider_or_fit_parameter_set' and 'sweep_parameter_set'
