### ISSUE TITLE
Button positioning 

### ISSUE THREAD

**Issue by Harrinive** [scqubits/qfit#20]
result -> fit button position too far way
Fit buttons should not be as small as the other ones

**Comment by ZhaoTianPu** [comment]
Improved UI/UX designs made by Tianying and implemented in 0bdc84c784183b82ade56fa8dd9cd604a2223241, 3c8eae3e12ee4c7a1b486f4e479c0f293444d333, and de9472d8ab6bbc211d659e445967e649328df673.
