### ISSUE TITLE
I dont see any gui?

### ISSUE THREAD

**Issue by ahkatlio** [scqubits/qfit#3]
![image](https://github.com/scqubits/qfit/assets/109025616/398714e4-8651-40e7-ab5b-5117a5be5230)
## No GUI

**Comment by ahkatlio** [comment]
Oh found it

**Comment by ahkatlio** [comment]
Found it but only after running separately

**Comment by ZhaoTianPu** [comment]
Thank you very much for your interests in our app! Could you elaborate more on what you meant by "only after running separately"? Did you mean the behavior that when the cell is run, the app appears in a separate window?

**Comment by ahkatlio** [comment]
> Thank you very much for your interests in our app! Could you elaborate more on what you meant by "only after running separately"? Did you mean the behavior that when the cell is run, the app appears in a separate window?

yes
