### ISSUE TITLE
Issue with setup file

### ISSUE THREAD

**Issue by shelendergp** [scqubits/qfit#38]
Hi 
I saw an issue with the  setup file and this is related with **ui_views** and I think you have **views** in your directory.

Thanks

**Comment by ZhaoTianPu** [comment]
Apologies and thanks for reporting, now the issue should have fixed with [27490e31f5381e41c57712ee1d0bc64fb6f762dc](https://github.com/scqubits/qfit/commit/27490e31f5381e41c57712ee1d0bc64fb6f762dc)
