### ISSUE TITLE
Cursor glitch

### ISSUE THREAD

**Issue by ahkatlio** [scqubits/qfit#4]
https://github.com/scqubits/qfit/assets/109025616/f76e9e81-7311-4af1-8db1-75a9b9ba9500

#### The mouse is kinda glitchy

**Comment by ZhaoTianPu** [comment]
Thank for reporting. Could you please tell us which operating system are you running the app on? We have previously observed laggy mouse on macOS (with M1 chip), where the glitch happens when the package requirements are installed through pip install. Performing conda install resolved problems in that case.

**Comment by ahkatlio** [comment]
Windows 11, after that I tried to modify the code, the main problem with was the calculation wasn't fast enough, so I tried to use GPU and tried to modify it but unfortunately PySide6 doesn't GPU

**Comment by ZhaoTianPu** [comment]
Thanks for narrowing down the problem. What did you mean by
> you can improve the help tabs because the title bar and the logo isnt defined there
? Did you mean the title bar is missing on windows, and you suggest including a menu bar with a help tab? From what I understand, the title bar only shows the title (and possibly icon) for the app, and has nothing to do with help.

LaTeX support would be a great thing to implement, and it seems like QWebEngineView would work with HTML (and hence render MathJax expressions). We will explore this option after the first release. Thanks for the suggestion!

**Comment by ahkatlio** [comment]
![image](https://github.com/scqubits/qfit/assets/109025616/57068830-9943-4941-9467-947e28260a15)

**Comment by ahkatlio** [comment]
Hello, can I contribute on this?

**Comment by ZhaoTianPu** [comment]
Apologies for our late response. Yes you are welcomed to make suggested edits and create PR! For accepted PR we will credit for your contributions properly.
