### ISSUE TITLE
Improve quick start notebook

### ISSUE THREAD

**Issue by ZhaoTianPu** [scqubits/qfit#8]
- [x] add a "pro tip" for how user can save computation time
- [x] remind user that x axis is the swept parameter, y axis is the frequency
- [x] A more detailed adding transition and labelling procedure is needed.
- [x] Step-by-step calibration process
- [x] remind user that the transitions may not necessarily start from 0
- [x] Emphasize x- and y-snapping features in the app
- [x] Emphasize how to delete a datapoint
- [x] Introduce what are the dashed lines.

**Comment by ahkatlio** [comment]
can i help you with documentation?

**Comment by ZhaoTianPu** [comment]
Apologies for our late reply. Yes please feel free to make suggestions on our quick start notebook by submitting pull requests! We'd love to learn what user (you) think would be most useful.
